sudo: true
language: python

matrix:
  fast_finish: true
  include:
  - python: 2.7
    env:
    - PYTHON_VERSION="2.7"

notifications:
  slack: colour-science:Y6lPPcN7y53Js94geqUpqsAP

addons:
  apt:
   sources:
      - ubuntu-toolchain-r-test
   packages:
      - libboost-all-dev
      - libopenexr-dev
      - libilmbase-dev

before_install:
  - wget https://github.com/OpenImageIO/oiio/archive/Release-1.5.21.tar.gz -O /tmp/OpenImageIO-1.5.21.tar.gz
  - tar -xvf /tmp/OpenImageIO-1.5.21.tar.gz
  - cd oiio-Release-1.5.21
  - make
  - cd /home/travis/build/colour-science/colour-checker-detection
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes --quiet conda

install:
  - conda create --yes --quiet -n colour-checker-detection-ci python=${PYTHON_VERSION} coverage coveralls flake8 matplotlib mock nose
  - source activate colour-checker-detection-ci
  - conda install -y -c conda-forge colour-science opencv=3.4.7
  - sudo cp /home/travis/build/colour-science/colour-checker-detection/oiio-Release-1.5.21/dist/linux64/bin/* /usr/local/bin/
  - sudo cp /home/travis/build/colour-science/colour-checker-detection/oiio-Release-1.5.21/dist/linux64/lib/* /usr/local/lib/
  - cp /home/travis/build/colour-science/colour-checker-detection/oiio-Release-1.5.21/dist/linux64/python/OpenImageIO.so /home/travis/miniconda/envs/colour-checker-detection-ci/lib/python2.7/site-packages/

script:
  - flake8 colour_checker_detection
  - nosetests --nocapture --with-doctest --doctest-options=+ELLIPSIS,+NORMALIZE_WHITESPACE --with-coverage --cover-package=colour_checker_detection colour_checker_detection

after_success:
  - coveralls
