sudo: true
language: python

matrix:
  fast_finish: true
  include:
  - python: 2.7
    env:
    - PYTHON_VERSION="2.7"

notifications:
  slack: colour-science:Y6lPPcN7y53Js94geqUpqsAP

addons:
  apt:
   sources:
      - ubuntu-toolchain-r-test
   packages:
      - libboost-all-dev
      - libopenexr-dev
      - libilmbase-dev

before_install:
  - wget http://repo.continuum.io/miniconda/Miniconda-latest-Linux-x86_64.sh -O miniconda.sh
  - chmod +x miniconda.sh
  - ./miniconda.sh -b -p /home/travis/miniconda
  - export PATH=/home/travis/miniconda/bin:$PATH
  - conda update --yes --quiet conda
  - PACKAGES="python=${PYTHON_VERSION}"
  - PACKAGES="${PACKAGES} numpy"; if [ ${NUMPY_VERSION} ]; then PACKAGES="${PACKAGES}=${NUMPY_VERSION}"; fi
  - PACKAGES="${PACKAGES} matplotlib"; if [ ${MATPLOTLIB_VERSION} ]; then PACKAGES="${PACKAGES}=${MATPLOTLIB_VERSION}"; fi
  - PACKAGES="${PACKAGES} scipy"; if [ ${SCIPY_VERSION} ]; then PACKAGES="${PACKAGES}=${SCIPY_VERSION}"; fi
  - wget https://github.com/OpenImageIO/oiio/archive/Release-1.5.21.tar.gz -O /tmp/OpenImageIO-1.5.21.tar.gz
  - tar -xvf /tmp/OpenImageIO-1.5.21.tar.gz
  - cd oiio-Release-1.5.21
  - make
  - cd /home/travis/build/colour-science/colour-checker-detection

install:
  - conda create --yes --quiet -n colour-checker-detection-test ${PACKAGES} pip setuptools nose
  - source activate colour-checker-detection-test
  - pip install colour-science coverage coveralls flake8 mock==1.0.1
  - sudo cp /home/travis/build/colour-science/colour-checker-detection/oiio-Release-1.5.21/dist/linux64/bin/* /usr/local/bin/
  - sudo cp /home/travis/build/colour-science/colour-checker-detection/oiio-Release-1.5.21/dist/linux64/lib/* /usr/local/lib/
  - cp /home/travis/build/colour-science/colour-checker-detection/oiio-Release-1.5.21/dist/linux64/python/OpenImageIO.so /home/travis/miniconda/envs/colour-checker-detection-test/lib/python2.7/site-packages/

script:
  - flake8 colour_checker_detection
  - nosetests --nocapture --with-doctest --doctest-options=+ELLIPSIS,+NORMALIZE_WHITESPACE --with-coverage --cover-package=colour_checker_detection colour_checker_detection

after_success:
  - coveralls
